### ISSUE TITLE
Arch Compatibility

### ISSUE THREAD

**Issue by HFDan** [zeankundev/suside#4]
It would be awesome to use the most sus code editor on arch linux. AUR version when?

### Checklist (required)
- [x] My feature request hereby, is not a duplicate of the other request.
- [x] My feature request isn't a existing feature.

**Comment by zeankundev** [comment]
I have deployed a RPM file in the releases, please check it out. It should work with Arch LInux since I don't have an AUR VM, I only test suside in Ubuntu and works well. So I think download your RPM.

**Comment by zeankundev** [comment]
But, Suside is based on Electron, so you need to install a desktop first and GLIBC library, then download the RPM from our release

**Comment by HFDan** [comment]
I have taken it upon myself to maintain an AUR PKGBUILD, that can be found [here](https://aur.archlinux.org/packages/suside-bin/). It currently installs SusIDE version 2.3.3

**Comment by zeankundev** [comment]
For the maintainer, please use the real authors name.
![Screenshot_20211219-123448_Edge.jpg](https://user-images.githubusercontent.com/58360911/146665167-92dcece4-b6f0-4b56-b164-26a142d445f0.jpg)

**Comment by HFDan** [comment]
I see what you mean, however maintainer in this case refers to the maintainer of the PKGBUILD, not of the upstream project.

Updating the PKGBUILD to install 2.3.3.1 is a little harder. While the git tag's name is "2.3.3.1", the file name only contains "2.3.3". This might require some additional processing of the version number, as i am against hardcoding stuff like this in links. If you could rename the release file to also read "2.3.3.1", it would be greatly appreciated, and would make my work easier.

**Comment by HFDan** [comment]
The PKGBUILD has been updated

**Comment by zeankundev** [comment]
Thank you!
