### ISSUE TITLE
dear god....

### ISSUE THREAD

**Issue by nxxh447** [zeankundev/suside#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

### Checklist (required)
- [ ] My feature request hereby, is not a duplicate of the other request.
- [ ] My feature request isn't a existing feature.

**Additional context**

**Comment by mobilegmYT** [comment]
er... did you accidently open this issue? theres no info about your issue in it

**Comment by zeankundev** [comment]
I think this is a false issue. I might have to close it, sorry!
